blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogDeleteView, BlogDetailView, BlogListView, BlogUpdateView, BlogCreateView
from catalog.views import home, contacts
from config import settings
from django.conf.urls.static import static

app_name = BlogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', contacts, name='contacts'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/list/', BlogListView.as_view(), name='blog_list'),
    path('blog/view/<int:pk>', BlogDetailView.as_view(), name='blog_view'),
    path('blog/edit/<int:pk>', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog'))
]
               + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
               + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS))

blog/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    body = models.CharField(verbose_name='содержимое')

    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    preview = models.ImageField(upload_to='preview/', verbose_name='изображение', **NULLABLE)
    date_create = models.DateTimeField(verbose_name='дата создания', auto_now_add=True)
    is_published = models.BooleanField(verbose_name='опубликовано', default=True)
    view_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return f'{self.title}, {self.view_count}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


# Create your views here.


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'preview',)
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        image = self.request.FILES.get('image')
        if image:
            new_blog = form.save(commit=False)
            new_blog.image = image
            new_blog.save()
        else:
            form.save()

        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)

        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body', 'preview',)

    # success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/includes/inc_blog.html
{% load my_tags %}
<style>
    .product-container {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
    }
    .product-card {
      width: 100%;
      border: 1px solid #ccc;
      border-radius: 5px;
      padding: 10px;
      margin-bottom: 20px;
    }

    .product-image {
      width: 100%;
      max-height: 300px;
      object-fit: cover;
      border-radius: 15px;
    }

    .product-name {
      font-size: 24px;
      font-weight: bold;
      margin-top: 16px;
    }

    .product-price {
      font-size: 24px;
    }

    .product-buttons {
      margin-top: 10px;
    }

    .product-buttons a {
      display: inline-block;
      padding: 5px 10px;
      background-color: #3498db;
      color: #fff;
      text-decoration: none;
      border-radius: 5px;
      margin-right: 5px;
    }

    .buy-button {
      background-color: #2ecc71;
    }

    .view-button {
      background-color: #f39c12;
    }

    .edit-button {
      background-color: #e67e22;
    }

    .delete-button {
      background-color: #c0392b;
    }
</style>

    <div class="product-container col-6">
        <div class="product-card">
            <img src="{{ object.preview | my_media }}" alt="{{ object.title }}" class="product-image">
            <h3 class="product-title">{{ object.title }}</h3>
            <p class="product-body">{{ object.body }}</p>
            <div class="product-buttons">
                <a href="{% url 'blog:blog_view' object.pk %}" class="view-button">Посмотреть</a>
                <a href="{% url 'blog:blog_edit' object.pk %}" class="edit-button">Редактировать</a>
                <a href="{% url 'blog:blog_delete' object.pk %}" class="delete-button">Удалить</a>
            </div>
        </div>
    </div>