blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogDeleteView, BlogDetailView, BlogListView, BlogUpdateView, BlogCreateView
from catalog.views import home, contacts
from config import settings
from django.conf.urls.static import static

app_name = BlogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', contacts, name='contacts'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/list/', BlogListView.as_view(), name='blog_list'),
    path('blog/view/<int:pk>', BlogDetailView.as_view(), name='blog_view'),
    path('blog/edit/<int:pk>', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import home, contacts, ProductCreateView, ProductListView, ProductDetailView, ProductUpdateView, \
    ProductDeleteView
from config import settings
from django.conf.urls.static import static

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', contacts, name='contacts'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/view/<int:pk>', ProductDetailView.as_view(), name='product_view'),
    path('product/edit/<int:pk>', ProductUpdateView.as_view(), name='product_edit'),
    path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog'))
]
               + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
               + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS))

catalog/models.py
from django.db import models

# Create your models here.

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='наименование')
    description = models.CharField(max_length=150, verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='наименование')
    description = models.CharField(max_length=150, verbose_name='описание')
    preview = models.ImageField(upload_to='preview/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена за покупку')
    date_creation = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    date_last_change = models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')

    def __str__(self):
        return f'Название: {self.name} Категория: {self.category}  Цена: {self.price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('price',)


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='товар')
    version = models.IntegerField(verbose_name='номер версии')
    name = models.CharField(max_length=100, verbose_name='название версии')
    is_active = models.BooleanField(default=True, verbose_name='активна')

    def __str__(self):
        return f'{self.name} {self.version} {self.is_active}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from catalog.models import Product


class ProductForm(forms.ModelForm):
    __forbidden_words = ['казино',
                         'криптовалюта',
                         'крипта',
                         'биржа',
                         'дешево',
                         'бесплатно',
                         'обман',
                         'полиция',
                         'радар']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Product
        fields = '__all__'

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        description = cleaned_data.get('description')

        for word in self.__forbidden_words:
            if word in name.lower() or word in description.lower():
                raise forms.ValidationError(f'В названии или в описании использовано запрещенное слово')
        return cleaned_data

catalog/views.py
from datetime import datetime

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from catalog.models import Product, Category
from catalog.forms import ProductForm


# Create your views here.

def home(request):
    context = {
        'object_list': Product.objects.all()[:3],
        'title': 'Топ товаров'
    }

    return render(request, 'catalog/home.html', context)


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name}, {phone}, {message}')
    return render(request, 'catalog/contacts.html')


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        image = self.request.FILES.get('image')
        if image:
            new_product = form.save(commit=False)
            new_product.image = image
            new_product.save()
        else:
            form.save()

        return super().form_valid(form)


class ProductListView(ListView):
    model = Product


class ProductDetailView(DetailView):
    model = Product


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

catalog/templates/catalog/includes/inc_products.html
{% load my_tags %}
<style>
    .product-container {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
    }
    .product-card {
      width: 100%;
      border: 1px solid #ccc;
      border-radius: 5px;
      padding: 10px;
      margin-bottom: 20px;
    }

    .product-image {
      width: 100%;
      max-height: 300px;
      object-fit: cover;
      border-radius: 15px;
    }

    .product-name {
      font-size: 24px;
      font-weight: bold;
      margin-top: 16px;
    }

    .product-price {
      font-size: 24px;
    }

    .product-buttons {
      margin-top: 10px;
    }

    .product-buttons a {
      display: inline-block;
      padding: 5px 10px;
      background-color: #3498db;
      color: #fff;
      text-decoration: none;
      border-radius: 5px;
      margin-right: 5px;
    }

    .buy-button {
      background-color: #2ecc71;
    }

    .view-button {
      background-color: #f39c12;
    }

    .edit-button {
      background-color: #e67e22;
    }

    .delete-button {
      background-color: #c0392b;
    }
</style>

    <div class="product-container col-6">
        <div class="product-card">
            <img src="{{ object.preview | my_media }}" alt="{{ object.name }}" class="product-image">
            <h3 class="product-name">{{ object.name }}</h3>
            <p class="product-price">{{ object.price }} руб</p>
            <div class="product-buttons">
                <a href="#" class="buy-button">Купить</a>
                <a href="{% url 'catalog:product_view' object.pk %}" class="view-button">Посмотреть</a>
                <a href="{% url 'catalog:product_edit' object.pk %}" class="edit-button">Редактировать</a>
                <a href="{% url 'catalog:product_delete' object.pk %}" class="delete-button">Удалить</a>
            </div>
        </div>
    </div>