blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogDeleteView, BlogDetailView, BlogListView, BlogUpdateView, BlogCreateView
from catalog.views import home, contacts
from config import settings
from django.conf.urls.static import static

app_name = BlogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', contacts, name='contacts'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/list/', BlogListView.as_view(), name='blog_list'),
    path('blog/view/<int:pk>', BlogDetailView.as_view(), name='blog_view'),
    path('blog/edit/<int:pk>', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import home, contacts, ProductCreateView, ProductListView, ProductDetailView, ProductUpdateView, \
    ProductDeleteView
from config import settings
from django.conf.urls.static import static

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', contacts, name='contacts'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/view/<int:pk>', ProductDetailView.as_view(), name='product_view'),
    path('product/edit/<int:pk>', ProductUpdateView.as_view(), name='product_edit'),
    path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog'))
]
               + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
               + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS))

catalog/models.py
from django.db import models

# Create your models here.

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='наименование')
    description = models.CharField(max_length=150, verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='наименование')
    description = models.CharField(max_length=150, verbose_name='описание')
    preview = models.ImageField(upload_to='preview/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена за покупку')
    date_creation = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    date_last_change = models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')

    def __str__(self):
        return f'Название: {self.name} Категория: {self.category}  Цена: {self.price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('price',)


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='товар')
    version = models.IntegerField(verbose_name='номер версии')
    name = models.CharField(max_length=100, verbose_name='название версии')
    is_active = models.BooleanField(default=True, verbose_name='активна')

    def __str__(self):
        return f'{self.name} {self.version} {self.is_active}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from catalog.models import Product


class ProductForm(forms.ModelForm):
    __forbidden_words = ['казино',
                         'криптовалюта',
                         'крипта',
                         'биржа',
                         'дешево',
                         'бесплатно',
                         'обман',
                         'полиция',
                         'радар']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Product
        fields = '__all__'

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        description = cleaned_data.get('description')

        for word in self.__forbidden_words:
            if word in name.lower() or word in description.lower():
                raise forms.ValidationError(f'В названии или в описании использовано запрещенное слово')
        return cleaned_data

catalog/views.py
from datetime import datetime

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from catalog.models import Product, Category
from catalog.forms import ProductForm


# Create your views here.

def home(request):
    context = {
        'object_list': Product.objects.all()[:3],
        'title': 'Топ товаров'
    }

    return render(request, 'catalog/home.html', context)


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name}, {phone}, {message}')
    return render(request, 'catalog/contacts.html')


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        image = self.request.FILES.get('image')
        if image:
            new_product = form.save(commit=False)
            new_product.image = image
            new_product.save()
        else:
            form.save()

        return super().form_valid(form)


class ProductListView(ListView):
    model = Product


class ProductDetailView(DetailView):
    model = Product


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
    <link href="{% static 'css/docs.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/docs.css' %}" rel="stylesheet">
    <title>Bootstrap Example</title>
</head>
<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"></use>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'catalog:home' %}" class="nav-link px-2 text-secondary">Главная</a></li>
                <li><a href="{% url 'catalog:contacts' %}" class="nav-link px-2 text-white">Контакты</a></li>
                <li><a href="{% url 'catalog:product_list'%}" class="nav-link px-2 text-white">Все товары</a>
                </li>
                <li><a href="{% url 'catalog:product_create'%}" class="nav-link px-2 text-white">Добавить товар</a>
                </li>
                <li><a href="{% url 'blog:blog_list'%}" class="nav-link px-2 text-white">Все блоги</a>
                </li>
                <li><a href="{% url 'blog:blog_create'%}" class="nav-link px-2 text-white">Добавить блог</a>
                </li>

                <li><a href="#" class="nav-link px-2 text-white"></a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search" class="form-control form-control-dark" placeholder="Поиск..." aria-label="Search">
            </form>

            <div class="text-end">
                <button type="button" class="btn btn-outline-light me-2">Вход</button>
                <button type="button" class="btn btn-warning">Регистрация</button>
            </div>
        </div>
    </div>
</header>

<div class="container ">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">SkyStore</h1>
            <p class="fs-5 text-body-secondary">{{ title }}</p>
        </div>
    </header>
    <main class="row">
        {% block content %}
        {% endblock %}
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-10 fw-normal text-body-emphasis">F.A.Q.</h1>

            <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            <strong>Как купить?</strong>
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            Оплата происходит онлайн, через личный кабинет. Для этого вам нужно всего-то
                            зарегестрироваться на нашем сайте!
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            <strong>Какая гарантия?</strong>
                        </button>
                    </h2>
                    <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            Гарантия на наши товары действует в течении одного года, нам важен ваш комформ и
                            бозопасность.
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            <strong>Как заказать доставку?</strong>
                        </button>
                    </h2>
                    <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            Доставку действует по всей России. Оформиить ее можно при оплате заказа.
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Example Code -->
        </div>
    </main>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small"></ul>
            </div>
        </div>
    </footer>
</div>
</body>
</html>

catalog/templates/catalog/categories.html
{% extends 'catalog/base.html' %}

{% block content %}
{% for object in object_list %}
<div class="col-4">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3">
            <h4 class="my-0 fw-normal">{{ object.name }}</h4>
        </div>
        <div class="card-body">
            <p>{{ object.description }}</p>
            <div>
                <p>
                    <a href="{% url 'catalog:category_product' object.pk %}" type="button"
                       class="h-100 btn btn-lg btn-secondary text-grey">Перейти к товарам
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/category_product.html
{% extends 'catalog/base.html' %}

{% block content %}
{% for object in object_list %}
    {% include 'catalog/includes/inc_products.html' %}
{% endfor %}
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/create_product.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="form-floating">
    {% csrf_token %}
    <div class="input-group p-1 pricing-header pb-md-4">
        <input type="text" class="form-control" name="name" maxlength="50" required id="id_name"
               placeholder="Наименование">
    </div>


    <div class="input-group p-1 pricing-header pb-md-4">
        <input type="text" name="description" maxlength="150" required id="id_description" placeholder="Описание">
    </div>
    <div class="input-group p-1 pricing-header pb-md-4">
        <input type="file" name="preview" accept="media/image/" id="id_preview" placeholder="Изображение">
    </div>
    <div class="input-group pricing-header pb-md-4">
        <label for="id_category">Категория:</label>
        <select name="category" required id="id_category">
            <option value="" selected>---------</option>
            {% for object in object_list %}-->
            <option value="{{ object.id }}">{{ object.name }}</option>
            {% endfor %}

<!--            <option value="1">название: Ноутбуки описание: Многофункциональное устройство для работы и развлечения-->
<!--            </option>-->

<!--            <option value="3">название: Портативные колонки описание: Устройство для прослушивания ваших любимых треков-->
<!--                в хорошем качестве-->
<!--            </option>-->

<!--            <option value="2">название: Смартфоны описание: Компактное устройсво с огромным функционалом, которое всегда-->
<!--                под рукой-->
<!--            </option>-->

        </select>
    </div>
    <div class="input-group p-1 pricing-header pb-md-4">
        <input type="number" name="price" required id="id_price" placeholder="Цена за покупку">
    </div>
    <div class="input-group p-1 pricing-header pb-md-4">
        <input type="text" name="date_creation" required id="id_date_creation" placeholder="Дата создания:">
    </div>
    <div class="input-group p-1 pricing-header pb-md-4">
        <input type="text" name="date_last_change" required id="id_date_last_change"
               placeholder="Дата последнего изменения:">
    </div>
    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
</form>

<!--    <div class="input-group p-1 pricing-header pb-md-4">-->
<!--        <input type="text" name="name" class="form-control" id="name" placeholder="Название товара" required>-->
<!--    </div>-->

<!--    <div class="input-group p-1 pricing-header pb-md-4">-->
<!--        <label class="input-group-text" for="inputGroupSelect01">Категория</label>-->
<!--        <select name='category' class="form-select" id="inputGroupSelect01">-->
<!--            <option selected>...</option>-->
<!--            {% for object in object_list %}-->
<!--            <option name='category' value="{{ object.name }}">{{ object.name }}</option>-->
<!--            {% endfor %}-->
<!--        </select>-->
<!--    </div>-->
<!--    <div class="input-group p-1 pricing-header pb-md-4">-->
<!--        <input type="text" name="price" class="form-control" id="price" placeholder="Цена" required>-->
<!--    </div>-->

<!--    <div class="input-group p-1 pricing-header pb-md-4">-->
<!--        <input type="file" class="form-control" id="image" name="image">-->
<!--    </div>-->

<!--    <div class="input-group p-1 pricing-header pb-md-4">-->
<!--        <span class="input-group-text p-3 pricing-header pb-md-4 mx-auto text-center">Добавьте описание</span>-->
<!--        <textarea class="form-control" aria-label="With textarea" id="description" name="description" required></textarea>-->
<!--    </div>-->
<!--    <div class="col-1">-->
<!--        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>-->
<!--    </div>-->
<!--</form>-->
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    {% for object in object_list %}
    {% include 'catalog/includes/inc_products.html' %}
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<style>
    img {
        width: 1000px;
        height: 900;
    }
</style>
<div class="bd-content ps-lg-2">

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <p class="fs-1 text-body-secondary">{{ object_list.name }}</p>
            <img src="{{ object_list.preview | my_media }}"/>
        </div>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <p class="fs-4 text-body-secondary">{{ object_list.description }}</p>
        </div>
    </header>
    <!--    <h1 id="headings">{{ object_list.name }}<a class="text" href=""></a>-->
    <!--    </h1>-->
    <!--    <img src="{{ object_list.preview | my_media }}"/>-->
    <!--    <div class="bd-example-snippet bd-code-snippet">-->
    <!--        <div class="bd-example m-0 border-0">-->
    <!--            <h2>{{ object_list.description }}</h2>-->
    <!--&lt;!&ndash;        </div>&ndash;&gt;-->
    <!--    </div>-->
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <form method="post" class="">
                    {% csrf_token %}
                    <p>Хотите удалить товар "{{ object.name }}" ?</p>
                    <button type="submit" class="btn btn-success">Подтвердить
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<style>
    img {
        width: 1000px;
        height: 900;
    }
</style>
<div class="bd-content ps-lg-2">

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <p class="fs-1 text-body-secondary">{{ object.name }}</p>
            <img src="{{ object.preview | my_media }}"/>
        </div>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <p class="fs-4 text-body-secondary">{{ object.description }}</p>
        </div>
    </header>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12 ">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    {% for object in object_list %}
    {% include 'catalog/includes/inc_products.html' %}
    {% endfor %}
{% endblock %}